
import java.sql.SQLException;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author JaimeLap
 */
public class AltaResidente extends javax.swing.JFrame {

    /**
     * Creates new form MuestraResidentes
     */
    private ConectaBBDD con;
    
    public AltaResidente() {

            initComponents();
            setLocationRelativeTo(null);
            setResizable(false);   
            jTmatricula.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTmarca = new javax.swing.JTextField();
        jTmodelo = new javax.swing.JTextField();
        jRadio3p = new javax.swing.JRadioButton();
        jRadio5p = new javax.swing.JRadioButton();
        jBanyadir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jBcancelar = new javax.swing.JButton();
        jComboTipo = new javax.swing.JComboBox<>();
        jComboColor = new javax.swing.JComboBox<>();
        jTmatricula = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("INTRODUCE UN RESIDENTE NUEVO");

        jLabel2.setText("Marca");

        jLabel3.setText("Modelo");

        jLabel4.setText("Tipo");

        jLabel5.setText("Color");

        jLabel6.setText("Puertas");

        buttonGroup1.add(jRadio3p);
        jRadio3p.setSelected(true);
        jRadio3p.setText("3 Puertas");

        buttonGroup1.add(jRadio5p);
        jRadio5p.setText("5 Puertas");

        jBanyadir.setText("Añadir");
        jBanyadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBanyadirActionPerformed(evt);
            }
        });

        jLabel7.setText("Matrícula");

        jBcancelar.setText("Cancelar");
        jBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelarActionPerformed(evt);
            }
        });

        jComboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monovolumen", "Berlina", "Familiar", "Todoterreno" }));
        jComboTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboTipoActionPerformed(evt);
            }
        });

        jComboColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rojo", "Blanco", "Negro", "Gris Plata", "Gris Grafito", "Azul", "Verde", "Amarillo", " " }));

        try {
            jTmatricula.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-UUU")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTmatricula.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jRadio3p)
                                .addGap(18, 18, 18)
                                .addComponent(jRadio5p))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTmarca)
                                        .addComponent(jTmatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                                    .addComponent(jComboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBanyadir)
                .addGap(18, 18, 18)
                .addComponent(jBcancelar)
                .addGap(94, 94, 94))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jRadio3p)
                    .addComponent(jRadio5p))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBanyadir)
                    .addComponent(jBcancelar))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBcancelarActionPerformed

    private void jBanyadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBanyadirActionPerformed
        // TODO add your handling code here:
       
            String matricula = jTmatricula.getText();
            String marca = jTmarca.getText();
            String modelo = jTmodelo.getText();
            String tipo = "0"+(jComboTipo.getSelectedIndex()+1);
            String color = jComboColor.getSelectedItem().toString();
            int numPuertas;            
            if (jRadio3p.isSelected()) {
                numPuertas = 3;
            } else {
                numPuertas = 5;
            }
      
            Vehiculo vehiculo = new Residente(marca, modelo, tipo, color, numPuertas, matricula, numPuertas);
            //CONECTA BASE
        String sql;
        int error;
        Calendar instante;
        instante = Calendar.getInstance();
        String fechaAlta;
        fechaAlta = calendarToStringDate(instante);
        try {
            con = new ConectaBBDD();
            con.conecta();
            con.crearSentencia();
            sql = "INSERT INTO vehiculos (matricula, marca, modelo, tipo, color, numPuertas, tiempoAcumulado, fechaAlta, clase) VALUES ('"+matricula+"', '"+marca+"', '"+modelo+"', '"+tipo+"', '"+color+"', '"+numPuertas+"', '0', '"+fechaAlta+"', '01'); ";
            error = con.updateSQL(sql);
            if(error==1)                  
              JOptionPane.showMessageDialog(this,"Vehiculo insertado","AVISO",JOptionPane.INFORMATION_MESSAGE);
            
              else 
               JOptionPane.showMessageDialog(this,"Vehiculo no insertado","AVISO",JOptionPane.INFORMATION_MESSAGE);
            con.cerrarConexion();
            this.dispose();
        
        }
        catch (SQLException ex) {
             JOptionPane.showMessageDialog(this,ex.getMessage(),"AVISO",JOptionPane.ERROR_MESSAGE);
 
        }
        catch (Exception ex) {
             JOptionPane.showMessageDialog(this,ex.getMessage(),"AVISO",JOptionPane.ERROR_MESSAGE);
        }  
    }//GEN-LAST:event_jBanyadirActionPerformed

    private void jComboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboTipoActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBanyadir;
    private javax.swing.JButton jBcancelar;
    private javax.swing.JComboBox<String> jComboColor;
    private javax.swing.JComboBox<String> jComboTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadio3p;
    private javax.swing.JRadioButton jRadio5p;
    private javax.swing.JTextField jTmarca;
    private javax.swing.JFormattedTextField jTmatricula;
    private javax.swing.JTextField jTmodelo;
    // End of variables declaration//GEN-END:variables
    
    
public static final String calendarToStringDate(Calendar cal) {
    StringBuilder ret = new StringBuilder();
    ret.append(cal.get(Calendar.YEAR));
    ret.append("-");
      
    String month = null;
    int mo = cal.get(Calendar.MONTH) + 1; /* Calendar month is zero indexed, string months are not */
    if(mo < 10) {
        month = "0" + mo;
    }
      else {
        month = "" + mo;
    }
    ret.append(month);      
    ret.append("-");
    String date = null;
    int dt = cal.get(Calendar.DATE);
    if(dt < 10) {
        date = "0" + dt;
    }
      else {
        date = "" + dt;
    }
    ret.append(date);

    return ret.toString();
  }
   
    
}

