
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author JaimeLap
 */
public class BorrarResidente extends javax.swing.JFrame {

    /**
     * Creates new form MuestraVehiculos
     */
    private ConectaBBDD con;
    
    public BorrarResidente() {

            initComponents();
            setLocationRelativeTo(null);
            setResizable(false);
            bloqueaCampos();
            llenaCombo();
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTmarca = new javax.swing.JTextField();
        jTmodelo = new javax.swing.JTextField();
        jTtipo = new javax.swing.JTextField();
        jTcolor = new javax.swing.JTextField();
        jRadio3p = new javax.swing.JRadioButton();
        jRadio5p = new javax.swing.JRadioButton();
        jBborrar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboMatricula = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("BORRAR RESIDENTE");

        jLabel2.setText("Marca");

        jLabel3.setText("Modelo");

        jLabel4.setText("Tipo");

        jLabel5.setText("Color");

        jLabel6.setText("Puertas");

        jTcolor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTcolorActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadio3p);
        jRadio3p.setSelected(true);
        jRadio3p.setText("3 Puertas");

        buttonGroup1.add(jRadio5p);
        jRadio5p.setText("5 Puertas");

        jBborrar.setText("Borrar");
        jBborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBborrarActionPerformed(evt);
            }
        });

        jLabel7.setText("Matrícula");

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jBborrar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addComponent(jRadio3p)
                                .addGap(18, 18, 18)
                                .addComponent(jRadio5p))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(45, 45, 45))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(jLabel7)
                                        .addGap(31, 31, 31)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                                        .addComponent(jButton1))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTcolor, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTtipo, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTmodelo, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTmarca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel1))))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jComboMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTcolor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jRadio3p)
                    .addComponent(jRadio5p))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBborrar)
                    .addComponent(jButton2))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTcolorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTcolorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTcolorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sql;
        jBborrar.setEnabled(true);
        jButton2.setEnabled(true);
        try {
            con = new ConectaBBDD();
            con.conecta();
            con.crearSentencia();
            sql = "SELECT * FROM vehiculos where matricula = '"+jComboMatricula.getSelectedItem()+"'";
            con.ejecutaSQL(sql); 
            if(con.rs.next()) {                  
                    mostrar();
            }
          else
              JOptionPane.showMessageDialog(this,"Matricula no encontrada","AVISO",JOptionPane.INFORMATION_MESSAGE);
          
        }
        catch (SQLException ex) {
            Logger.getLogger(MuestraVehiculos.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (Exception e) {
                e.printStackTrace();
            }
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jBborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBborrarActionPerformed
        // TODO add your handling code here:
        String sql;
        int error;
        try {
            con = new ConectaBBDD();
            con.conecta();
            con.crearSentencia();
            sql = "DELETE FROM vehiculos where matricula = '"+jComboMatricula.getSelectedItem()+"'";
            error = con.updateSQL(sql);
            if(error==1) {                  
              JOptionPane.showMessageDialog(this,"Vehiculo borrado","AVISO",JOptionPane.INFORMATION_MESSAGE);
            }  
            if (error == -1)
                JOptionPane.showMessageDialog(this,"El vehículo está en el parking","AVISO",JOptionPane.INFORMATION_MESSAGE);
         
            this.dispose();
        }
        catch (SQLException ex) {
             JOptionPane.showMessageDialog(this,ex.getMessage(),"AVISO",JOptionPane.ERROR_MESSAGE);
 
        }
        catch (Exception ex) {
             JOptionPane.showMessageDialog(this,ex.getMessage(),"AVISO",JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_jBborrarActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBborrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboMatricula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadio3p;
    private javax.swing.JRadioButton jRadio5p;
    private javax.swing.JTextField jTcolor;
    private javax.swing.JTextField jTmarca;
    private javax.swing.JTextField jTmodelo;
    private javax.swing.JTextField jTtipo;
    // End of variables declaration//GEN-END:variables
    
    private void mostrar() {         
        try {
            jTmarca.setText(con.rs.getString("marca"));
            jTmodelo.setText(con.rs.getString("modelo"));
            jTtipo.setText(con.rs.getString("tipo"));  
            jTcolor.setText(con.rs.getString("color"));
            if (con.rs.getInt("numPuertas")==3)
                jRadio3p.setSelected(true);
            else 
                jRadio5p.setSelected(true);
            
        } catch (SQLException ex) {
            Logger.getLogger(MuestraVehiculos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    void bloqueaCampos() {
        jTmarca.setEditable(false);
        jTmodelo.setEditable(false);
        jTtipo.setEditable(false);
        jTcolor.setEditable(false);
        jBborrar.setEnabled(false);
        jButton2.setEnabled(false);
    }
        private void llenaCombo() {
        try {
            ConectaBBDD con = new ConectaBBDD();
            con.conecta();
            con.crearSentencia();
            String sql = "SELECT * FROM vehiculos where clase = '01'";
            con.ejecutaSQL(sql);
            DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
    
            while (con.rs.next())
            
            modeloCombo.addElement(con.rs.getString("matricula"));  
             
            
             jComboMatricula.setModel(modeloCombo);//con esto lo agregamos al objeto al jcombobox
             con.cerrarConexion();
        } catch (SQLException ex) {
            Logger.getLogger(EntradaSalida.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
}

