
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JaimeLap
 */
public class Ejercicio4 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio4
     */
    ConectaBBDD con = new ConectaBBDD();
  
    
    public Ejercicio4() {
        initComponents();
        setLocationRelativeTo(null);
        precioMotos();
        precioResidentes();
        precioNoResidentes();
        precioVehiculos();
        cuentaEstancias();
        cuentaVehiculos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTprecioVehi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTprecioNoResi = new javax.swing.JTextField();
        jTprecioResi = new javax.swing.JTextField();
        jTcountResidentes = new javax.swing.JTextField();
        jTcountEstancias = new javax.swing.JTextField();
        jTprecioMotos = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("PRECIO TODOS VEHICULOS");

        jLabel2.setText("PRECIO RESIDENTES");

        jLabel3.setText("PRECIO NO RESIDENTES");

        jLabel4.setText("PRECIO MOTOS");

        jLabel5.setText("CANTIDAD ESTANCIAS");

        jLabel6.setText("CANTIDAD RESIDENTES");

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTprecioMotos, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTcountEstancias, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTcountResidentes, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTprecioNoResi, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTprecioVehi, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTprecioResi, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTprecioVehi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTprecioResi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTprecioNoResi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jTprecioMotos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTcountEstancias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTcountResidentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTcountEstancias;
    private javax.swing.JTextField jTcountResidentes;
    private javax.swing.JTextField jTprecioMotos;
    private javax.swing.JTextField jTprecioNoResi;
    private javax.swing.JTextField jTprecioResi;
    private javax.swing.JTextField jTprecioVehi;
    // End of variables declaration//GEN-END:variables

 
    private void precioResidentes() {
        try {
            Residente resi = null;
            double precio = resi.getPrecioMinuto();
            con.conecta();
            con.crearSentencia();
            String sql = "SELECT SUM(tiempoAcumulado) AS tiempoVehiculos FROM vehiculos WHERE clase = '01'";
            con.ejecutaSQL(sql);
            con.rs.first();
            double consulta = con.rs.getDouble("tiempoVehiculos");
            double resultado = consulta*precio;     
            jTprecioResi.setText(String.valueOf(resultado));
            con.cerrarConexion();
        } catch (SQLException ex) {
            Logger.getLogger(Ejercicio4.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void precioNoResidentes() {
        try {
            NoResidente noResi = null;
            double precio = noResi.getPrecioMinuto();
            con.conecta();
            con.crearSentencia();
            String sql = "SELECT SUM(tiempoAcumulado) AS tiempoVehiculos FROM vehiculos WHERE clase = '02'";
            con.ejecutaSQL(sql);
            con.rs.first();
            double consulta = con.rs.getDouble("tiempoVehiculos");
            double resultado = consulta*precio;     
            jTprecioNoResi.setText(String.valueOf(resultado));
            con.cerrarConexion();
        } catch (SQLException ex) {
            Logger.getLogger(Ejercicio4.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void precioMotos() {
        try {
            Moto moto = null;
            double precio = moto.getPrecioMinuto();
            con.conecta();
            con.crearSentencia();
            String sql = "SELECT SUM(tiempoAcumulado) AS tiempoVehiculos FROM vehiculos WHERE clase = '03'";
            con.ejecutaSQL(sql);
            con.rs.first();
            double consulta = con.rs.getDouble("tiempoVehiculos");
            double resultado = consulta*precio;     
            jTprecioMotos.setText(String.valueOf(resultado));
            con.cerrarConexion();
        } catch (SQLException ex) {
            Logger.getLogger(Ejercicio4.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void precioVehiculos() {
        float resultado = 0;
        Float moto = Float.parseFloat(jTprecioMotos.getText());
        Float resi = Float.parseFloat(jTprecioResi.getText());
        Float NoResi = Float.parseFloat(jTprecioNoResi.getText());
        
        resultado = moto+resi+NoResi;
      
        jTprecioVehi.setText(String.valueOf(resultado));
    
    }
    private void cuentaEstancias() {
        try {
            ConectaBBDD con = new ConectaBBDD();
            String sql;
            con.conecta();
            con.crearSentencia();
            sql = "SELECT COUNT(*) AS plazas FROM estancias";
            con.ejecutaSQL(sql);
            con.rs.first();
            int resultado;
            resultado = con.rs.getInt("plazas");             
            jTcountEstancias.setText(String.valueOf(resultado));
            con.cerrarConexion();
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }    

    private void cuentaVehiculos() {
            try {
            ConectaBBDD con = new ConectaBBDD();
            String sql;
            con.conecta();
            con.crearSentencia();
            sql = "SELECT COUNT(*) AS residentes FROM vehiculos WHERE clase = '01'";
            con.ejecutaSQL(sql);
            con.rs.first();
            int resultado;
            resultado = con.rs.getInt("residentes");             
            jTcountResidentes.setText(String.valueOf(resultado));
            con.cerrarConexion();
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }
}
