import java.sql.SQLException;
import java.util.Calendar;
import static javafx.scene.paint.Color.color;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JaimeLap
 */
public class Ejercicio3 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio3
     */
    ConectaBBDD con = new ConectaBBDD();
    public Ejercicio3() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTmatricula = new javax.swing.JFormattedTextField();
        jTmarca = new javax.swing.JTextField();
        jTmodelo = new javax.swing.JTextField();
        jBanyadir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBcancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("AÑADE MOTOS AL PARKING");

        try {
            jTmatricula.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-UUU")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTmatricula.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N

        jBanyadir.setText("Añadir");
        jBanyadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBanyadirActionPerformed(evt);
            }
        });

        jLabel7.setText("Matrícula");

        jLabel3.setText("Marca");

        jBcancelar.setText("Cancelar");
        jBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelarActionPerformed(evt);
            }
        });

        jLabel4.setText("Modelo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addContainerGap(245, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(142, 142, 142)
                            .addComponent(jBanyadir)
                            .addGap(18, 18, 18)
                            .addComponent(jBcancelar))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(119, 119, 119)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel7)
                                .addComponent(jLabel3))
                            .addGap(31, 31, 31)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTmarca)
                                    .addComponent(jTmatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                                .addComponent(jTmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addContainerGap(328, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jTmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jTmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jTmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(151, 151, 151)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBanyadir)
                        .addComponent(jBcancelar))
                    .addContainerGap(47, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBanyadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBanyadirActionPerformed
        // TODO add your handling code here:
String matricula=jTmatricula.getText(),fecha;
        Vehiculo vehiculo= new NoResidente(matricula);
        Estancia esta;
        String sql, fechaHora = Calendar.getInstance().getTime().toString();
        Calendar instante;
        int error;
        ConectaBBDD con = new ConectaBBDD();
        try {
            con.conecta(); 
            con.crearSentencia();
            instante = Calendar.getInstance();
            fecha = calendarToStringTime(instante);
            sql = "INSERT INTO vehiculos (matricula,tipo,fechaAlta,clase) VALUES ('"+matricula+"','01','"+fecha+"','03')";
            System.out.println(sql);
            error = con.updateSQL(sql);
            if (error==-1){
                 JOptionPane.showMessageDialog(this,"Entrada de Moto Resisdente : "+matricula+", añadido con éxito","Entrada Residente",JOptionPane.INFORMATION_MESSAGE);
            }
            else
                 JOptionPane.showMessageDialog(this,"Entrada de Moto No residente: "+matricula+", añadido con éxito","Entrada No Residente",JOptionPane.INFORMATION_MESSAGE);
            instante = Calendar.getInstance();
            fechaHora = calendarToStringDate(instante);
            esta = new Estancia(matricula, instante);
            sql = "INSERT INTO estancias (matricula,horaEntrada) VALUES('"+esta.getMatricula()+"','"+fechaHora+"')";
            System.out.println(sql);
            error = con.updateSQL(sql);
            if (error != 1){
                JOptionPane.showMessageDialog(this,"ESTANCIA NO INSERTADA","ERROR",JOptionPane.ERROR_MESSAGE);    
                // DEBERÍA BORRAR LA ENTRADA EN VEHÍCULOS SI ES UN NO RESIDENTE
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this,"ERROR EN BBDD","ERROR",JOptionPane.ERROR_MESSAGE);
  
        }
        this.dispose();
    }//GEN-LAST:event_jBanyadirActionPerformed

    private void jBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBcancelarActionPerformed

    /**
     * @param args the command line arguments
     */
   public static final String calendarToStringDate(Calendar cal) {
    StringBuilder ret = new StringBuilder();
    ret.append(cal.get(Calendar.YEAR));
    ret.append("-");
      
    String month = null;
    int mo = cal.get(Calendar.MONTH) + 1; /* Calendar month is zero indexed, string months are not */
    if(mo < 10) {
        month = "0" + mo;
    }
      else {
        month = "" + mo;
    }
    ret.append(month);      
    ret.append("-");
    String date = null;
    int dt = cal.get(Calendar.DATE);
    if(dt < 10) {
        date = "0" + dt;
    }
      else {
        date = "" + dt;
    }
    ret.append(date);

    return ret.toString();
  }
   public static final String calendarToStringTime(Calendar cal) {
    StringBuilder ret = new StringBuilder();    
    String date = null;
    String month = null, hora = null, mini=null, seg=null;
    
   int mo,dt,hh,mm,ss;
    
    ret = ret.append(calendarToStringDate(cal));

    ret.append(" ");
    hh = cal.get(Calendar.HOUR_OF_DAY);
    if(hh < 10) {
        hora = "0" + hh+":";
    }
      else {
        hora = "" + hh+":";
    }
    ret.append(hora);
    mm = cal.get(Calendar.MINUTE);
    if(hh < 10) {
        mini = "0" + mm+":";
    }
      else {
        mini = "" + mm+":";
    }
    ret.append(mini);
    ss = cal.get(Calendar.SECOND);
    if(ss < 10) {
        seg = "0" + ss;
    }
      else {
        seg = "" + ss;
    }
    ret.append(seg);

    return ret.toString();
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBanyadir;
    private javax.swing.JButton jBcancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTmarca;
    private javax.swing.JFormattedTextField jTmatricula;
    private javax.swing.JTextField jTmodelo;
    // End of variables declaration//GEN-END:variables
}
