
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.ListIterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JaimeLap
 */
public class Ejercicio1 extends javax.swing.JFrame {

    /**
     * Creates new form ejercicio1
     * 
     */
    
    ArrayList<Residente> listaResi = new ArrayList<Residente>();
    Residente resi;

    
    public Ejercicio1() {
        
        initComponents();        
        llenaArrayList();
        setLocationRelativeTo(null);
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaResul = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Vehiculos residentes");

        jTextAreaResul.setColumns(20);
        jTextAreaResul.setRows(5);
        jScrollPane1.setViewportView(jTextAreaResul);

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel1))
                    .addComponent(jButton1))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaResul;
    // End of variables declaration//GEN-END:variables

    private void llenaArrayList ()  {
      //llena ArrayList con vehiculos de tipo Residente
        try {
          ArrayList<Vehiculo> listaVehiculos = new ArrayList();
            ConectaBBDD con = new ConectaBBDD();
            String matricula, tipo, color, marca, modelo,sql;
            int numPuertas, tiempoAcumulado, cont = 0;
            Residente vehiculo;
            String resultado = "";
            con.conecta();
            con.crearSentencia();
            sql = "SELECT * FROM vehiculos WHERE clase = '01'"; //recogemos datos de residentes          
            con.ejecutaSQL(sql);
            if (con.tamanyo()>0){
                
                do {
                    con.iralsiguiente();
                    vehiculo=con.dameResidenteActual();
                    resultado += "Matricula: "+vehiculo.getMatricula() + "\n"+
                                 "Marca: "+vehiculo.getMarca()+ "\n"+
                                 "Modelo: "+vehiculo.getModelo() + "\n"+  
                                 "Color: "+vehiculo.getColor() + "\n"+
                                 "Tipo: "+vehiculo.getTipo()+ "\n"+
                                 "Puertas:"+vehiculo.getNumPuertas()+ "\n"+
                                 "Tiempo acumulado: "+vehiculo.getTiempoAcumulado()+ "\n"+
                             
                            "--------------------------\n";
                           
                            ;
                } while (!con.esElUltimo());                
           // String[] myArrayDeStrings = array.toArray(new String[array.size()]);  
            }
            con.cerrarConexion();
            jTextAreaResul.setText(resultado);
            
        } catch (SQLException ex) {
            Logger.getLogger(Ejercicio1.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
   
}