
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author JaimeLap
 */
public class ModificarResidente extends javax.swing.JFrame {

    /**
     * Creates new form MuestraVehiculos
     */
    private ConectaBBDD con;
    
    public ModificarResidente() {

            initComponents();
            setLocationRelativeTo(null);
            setResizable(false);
            bloqueaCampos();
            llenaCombo();
           
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * 
     * Boton Buscar
     * si lo encuentra deshabilita el campo matricula y muestra los botones de abajo
     * habilita los campos editables
     * si no lo encuentra lo vuelve a pedir
     * 
     * Boton modificar
     * Recoger datos del formulario
     * Intentar hacer el update
     * 
     * 
     * 
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jRadio3p = new javax.swing.JRadioButton();
        jRadio5p = new javax.swing.JRadioButton();
        jBmodificar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jBbuscar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboTipo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboColor = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTmarca = new javax.swing.JTextField();
        jTmodelo = new javax.swing.JTextField();
        jComboMatricula = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("FICHAS RESIDENTES");

        jLabel6.setText("Puertas");

        buttonGroup1.add(jRadio3p);
        jRadio3p.setSelected(true);
        jRadio3p.setText("3 Puertas");

        buttonGroup1.add(jRadio5p);
        jRadio5p.setText("5 Puertas");

        jBmodificar.setText("Modificar Residente");
        jBmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmodificarActionPerformed(evt);
            }
        });

        jLabel7.setText("Matrícula");

        jBbuscar.setText("Buscar");
        jBbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbuscarActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Marca");

        jLabel3.setText("Modelo");

        jComboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monovolumen", "Berlina", "Familiar", "Todoterreno" }));

        jLabel4.setText("Tipo");

        jComboColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rojo", "Blanco", "Negro", "Gris Plata", "Gris Grafito", "Azul", "Verde", "Amarillo", " " }));

        jLabel5.setText("Color");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(54, 54, 54)
                            .addComponent(jBmodificar)
                            .addGap(18, 18, 18)
                            .addComponent(jButton2))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(jRadio3p)
                                    .addGap(18, 18, 18)
                                    .addComponent(jRadio5p))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(5, 5, 5)
                                    .addComponent(jLabel7)
                                    .addGap(151, 151, 151)
                                    .addComponent(jBbuscar)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTmodelo, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                .addComponent(jTmarca))
                            .addComponent(jLabel1))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBbuscar)
                        .addComponent(jComboMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jRadio3p)
                    .addComponent(jRadio5p))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBmodificar)
                    .addComponent(jButton2))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbuscarActionPerformed
        // TODO add your handling code here:
        
        String sql;
        jBmodificar.setEnabled(true);
        jButton2.setEnabled(true);
        try {
            con = new ConectaBBDD();
            con.conecta();
            con.crearSentencia();
            sql = "SELECT * FROM vehiculos where matricula = '"+jComboMatricula.getSelectedItem()+"'";
            con.ejecutaSQL(sql); 
            if(con.rs.next()) {                  
                    mostrar();
                    desbloqueaCampos();
                    jComboMatricula.getSelectedItem();
                   
            }
          else
              JOptionPane.showMessageDialog(this,"Matricula no encontrada","AVISO",JOptionPane.INFORMATION_MESSAGE);
          
        }
        catch (SQLException ex) {
            Logger.getLogger(MuestraVehiculos.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (Exception e) {
                e.printStackTrace();
            }
         
    }//GEN-LAST:event_jBbuscarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jBmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmodificarActionPerformed
        // TODO add your handling code here:
         
            String marca = jTmarca.getText();
            String modelo = jTmodelo.getText();
            String tipo = String.valueOf(jComboTipo.getSelectedIndex());
            String color = jComboColor.getSelectedItem().toString();
            int numPuertas;            
            if (jRadio3p.isSelected()) {
                numPuertas = 3;
            } else {
                numPuertas = 5;
            }
            
        String sql;
        int error;
        
        try {
            con = new ConectaBBDD();
            con.conecta();
            con.crearSentencia();
            sql = "UPDATE vehiculos SET marca = '"+marca+"', modelo = '"+modelo+"', tipo='"+tipo+"', color='"+color+"', numPuertas='"+numPuertas+"' WHERE matricula ='"+jComboMatricula.getSelectedItem()+"'";
              
            error = con.updateSQL(sql);
            if(error==1) {                  
              JOptionPane.showMessageDialog(this,"Vehiculo modificado","AVISO",JOptionPane.INFORMATION_MESSAGE);
            }  
            if (error == -1)
                JOptionPane.showMessageDialog(this,"No modificado","AVISO",JOptionPane.INFORMATION_MESSAGE);
         
            this.dispose();
        }
        catch (SQLException ex) {
             JOptionPane.showMessageDialog(this,ex.getMessage(),"AVISO",JOptionPane.ERROR_MESSAGE);
 
        }
        catch (Exception ex) {
             JOptionPane.showMessageDialog(this,ex.getMessage(),"AVISO",JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_jBmodificarActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBbuscar;
    private javax.swing.JButton jBmodificar;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboColor;
    private javax.swing.JComboBox<String> jComboMatricula;
    private javax.swing.JComboBox<String> jComboTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadio3p;
    private javax.swing.JRadioButton jRadio5p;
    private javax.swing.JTextField jTmarca;
    private javax.swing.JTextField jTmodelo;
    // End of variables declaration//GEN-END:variables
    
    private void mostrar() {         
        try {
            jTmarca.setText(con.rs.getString("marca"));
            jTmodelo.setText(con.rs.getString("modelo"));
            jComboTipo.setSelectedItem(con.rs.getString("tipo"));  
            jComboColor.setSelectedItem(con.rs.getString("color"));
            if (con.rs.getInt("numPuertas")==3)
                jRadio3p.setSelected(true);
            else 
                jRadio5p.setSelected(true);
            
        } catch (SQLException ex) {
            Logger.getLogger(MuestraVehiculos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    void bloqueaCampos() {
        jTmarca.setEditable(false);
        jTmodelo.setEditable(false);
        jComboColor.setEditable(false);
        jComboTipo.setEditable(false);
        jBmodificar.setEnabled(false);
        jButton2.setEnabled(false);
    }
        void desbloqueaCampos() {
        jTmarca.setEditable(true);
        jTmodelo.setEditable(true);
        jComboColor.setEditable(true);
        jComboTipo.setEditable(true);
        jBmodificar.setEnabled(true);
        jButton2.setEnabled(true);
    }
    private void llenaCombo() {
        try {
            ConectaBBDD con = new ConectaBBDD();
            con.conecta();
            con.crearSentencia();
            String sql = "SELECT * FROM vehiculos where clase = '01'";
            con.ejecutaSQL(sql);
            DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
    
            while (con.rs.next())
            
            modeloCombo.addElement(con.rs.getString("matricula"));  
             
            
             jComboMatricula.setModel(modeloCombo);//con esto lo agregamos al objeto al jcombobox
             con.cerrarConexion();
        } catch (SQLException ex) {
            Logger.getLogger(EntradaSalida.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
}

