
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author JaimeLap
 */
public class MuestraResidentes extends javax.swing.JFrame {

    /**
     * Creates new form MuestraVehiculos
     */
    private ConectaBBDD con;
    
    public MuestraResidentes() {
        try {
            initComponents();
            setLocationRelativeTo(null);
            setResizable(false);
            con = new ConectaBBDD();
            con.conecta();
            con.crearSentencia();
            con.ejecutaSQL("SELECT * FROM vehiculos where clase = 01");     
            try {
                if(con.rs.first())
                    mostrar();
                if (con.rs.isFirst()){
                    primero.setEnabled(false);
                    atras.setEnabled(false);
                    if (con.tamanyo() > 1){
                       adelante.setEnabled(true);
                       ultimo.setEnabled(true);
                    }
                  }
                else {
                  primero.setEnabled(true);
                  atras.setEnabled(true);
                  adelante.setEnabled(true);
                  ultimo.setEnabled(true);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        } catch (SQLException ex) {
            Logger.getLogger(MuestraVehiculos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTmatricula = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTacumulado = new javax.swing.JTextField();
        jTcolor = new javax.swing.JTextField();
        adelante = new javax.swing.JButton();
        jRadio3p = new javax.swing.JRadioButton();
        ultimo = new javax.swing.JButton();
        jRadio5p = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTmarca = new javax.swing.JTextField();
        jTmodelo = new javax.swing.JTextField();
        primero = new javax.swing.JButton();
        jTtipo = new javax.swing.JTextField();
        atras = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("FICHAS RESIDENTES");

        jLabel7.setText("Matricula");

        jLabel8.setText("Total Acumulado");

        jTacumulado.setEditable(false);
        jTacumulado.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        jTcolor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTcolorActionPerformed(evt);
            }
        });

        adelante.setText(">");
        adelante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adelanteActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadio3p);
        jRadio3p.setSelected(true);
        jRadio3p.setText("3 Puertas");

        ultimo.setText(">>");
        ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ultimoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadio5p);
        jRadio5p.setText("5 Puertas");

        jLabel2.setText("Marca");

        jLabel3.setText("Modelo");

        jLabel5.setText("Color");

        jLabel4.setText("Tipo");

        jLabel6.setText("Puertas");

        primero.setText("<<");
        primero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primeroActionPerformed(evt);
            }
        });

        atras.setText("<");
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });

        jLabel9.setText("€");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(30, 30, 30)
                        .addComponent(jTacumulado, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                    .addGap(31, 31, 31)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jRadio3p)
                                            .addGap(18, 18, 18)
                                            .addComponent(jRadio5p))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTcolor, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTtipo, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTmodelo, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTmarca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(primero)
                                    .addGap(18, 18, 18)
                                    .addComponent(atras)
                                    .addGap(18, 18, 18)
                                    .addComponent(adelante)
                                    .addGap(18, 18, 18)
                                    .addComponent(ultimo)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(31, 31, 31)
                                .addComponent(jTmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTcolor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadio3p)
                        .addComponent(jRadio5p)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atras)
                    .addComponent(adelante)
                    .addComponent(ultimo)
                    .addComponent(primero))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTacumulado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTcolorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTcolorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTcolorActionPerformed

    private void adelanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adelanteActionPerformed
        // TODO add your handling code here:
        try {
            try {
                if(con.rs.next())
                    mostrar();
            } catch (Exception ex) {
                ex.printStackTrace();
            }
            if (con.rs.isLast()){
                if (con.tamanyo() > 1){
                       primero.setEnabled(true);
                       atras.setEnabled(true);
                    }
                
                adelante.setEnabled(false);
                ultimo.setEnabled(false);
              }
            else {
                 primero.setEnabled(true);
                atras.setEnabled(true);
                adelante.setEnabled(true);
                ultimo.setEnabled(true);
            }

        } catch (SQLException ex) {
            Logger.getLogger(MuestraVehiculos.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_adelanteActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        // TODO add your handling code here:
  try {
            try {
                if(con.rs.previous())
                    mostrar();
            } catch (Exception ex) {
                ex.printStackTrace();
            }
            if (con.rs.isFirst()){
                primero.setEnabled(false);
                atras.setEnabled(false);
                if (con.tamanyo() > 1){
                       adelante.setEnabled(true);
                       ultimo.setEnabled(true);
                    }
              }
            else {
                primero.setEnabled(true);
                atras.setEnabled(true);
                adelante.setEnabled(true);
                ultimo.setEnabled(true);
            }

        } catch (SQLException ex) {
            Logger.getLogger(MuestraVehiculos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_atrasActionPerformed

    private void primeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primeroActionPerformed
        // TODO add your handling code here:
        try {
            try {
                if(con.rs.first())
                    mostrar();
            } catch (Exception e) {
                e.printStackTrace();
            }
            if (con.rs.isFirst()){
                    primero.setEnabled(false);
                    atras.setEnabled(false);
                    if (con.tamanyo() > 1){
                       adelante.setEnabled(true);
                       ultimo.setEnabled(true);
                    }
                  }
                else {
                  primero.setEnabled(true);
                  atras.setEnabled(true);
                  adelante.setEnabled(true);
                  ultimo.setEnabled(true);
                }
                    
        } catch (SQLException ex) {
            Logger.getLogger(MuestraVehiculos.class.getName()).log(Level.SEVERE, null, ex);
        }
                                           

    }//GEN-LAST:event_primeroActionPerformed

    private void ultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ultimoActionPerformed
        // TODO add your handling code here:
        try {
            try {
                if(con.rs.last())
                    mostrar();
            } catch (Exception ex) {
                ex.printStackTrace();
            }
            if (con.rs.isLast()){
                if (con.tamanyo() > 1){
                       primero.setEnabled(true);
                       atras.setEnabled(true);
                    }
                
                adelante.setEnabled(false);
                ultimo.setEnabled(false);
              }
            else {
                adelante.setEnabled(true);
                ultimo.setEnabled(true);
            }

        } catch (SQLException ex) {
            Logger.getLogger(MuestraVehiculos.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }//GEN-LAST:event_ultimoActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adelante;
    private javax.swing.JButton atras;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadio3p;
    private javax.swing.JRadioButton jRadio5p;
    private javax.swing.JTextField jTacumulado;
    private javax.swing.JTextField jTcolor;
    private javax.swing.JTextField jTmarca;
    private javax.swing.JTextField jTmatricula;
    private javax.swing.JTextField jTmodelo;
    private javax.swing.JTextField jTtipo;
    private javax.swing.JButton primero;
    private javax.swing.JButton ultimo;
    // End of variables declaration//GEN-END:variables
    
    private void mostrar() {         
        try {
            if (con.rs.getString("tipo").equalsIgnoreCase("01")) 
                jTtipo.setText("Monovolumen");
                else if (con.rs.getString("tipo").equalsIgnoreCase("02")) 
                jTtipo.setText("Berlina");
                else if (con.rs.getString("tipo").equalsIgnoreCase("03")) 
                jTtipo.setText("Familiar");
                else if (con.rs.getString("tipo").equalsIgnoreCase("04")) 
                jTtipo.setText("Todoterreno");
            
            Residente resi = null;
            jTmatricula.setText(con.rs.getString("matricula"));
            jTmarca.setText(con.rs.getString("marca"));
            jTmodelo.setText(con.rs.getString("modelo"));
            //jTtipo.setText(con.rs.getString("tipo"));  
            jTcolor.setText(con.rs.getString("color"));
            if (con.rs.getInt("numPuertas")==3)
                jRadio3p.setSelected(true);
            else 
                jRadio5p.setSelected(true);
            jTacumulado.setText(String.valueOf(con.rs.getInt("tiempoAcumulado")*resi.getPrecioMinuto()));
            
        } catch (SQLException ex) {
            Logger.getLogger(MuestraVehiculos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    void bloqueaCampos() {
        jTmatricula.setEditable(false);
        jTmarca.setEditable(false);
        jTmodelo.setEditable(false);
        jTtipo.setEditable(false);
        jTcolor.setEditable(false);
    }

   

}

